# Generated by Django 3.0.3 on 2020-03-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_maintenancestate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancestate',
            old_name='is_Maintenance',
            new_name='is_maintenance',
        ),
    ]
